import { ArrowLeft, CheckCircle2, ExternalLink, Globe2, LockKeyhole, Mail, MapPin, Phone, Sparkles, Star, XCircle } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Card } from "@/components/ui/card";
import { getLead, leads } from "@/lib/mock-data";
import { formatRelativeDate } from "@/lib/utils";

export function generateStaticParams() { return leads.map((lead) => ({ id: lead.id })); }

const scoreParts = [
  { key: "businessStrength", label: "İşletme gücü", max: 30, color: "bg-emerald-400" },
  { key: "digitalOpportunity", label: "Dijital fırsat", max: 30, color: "bg-amber-500" },
  { key: "commercialPotential", label: "Ticari potansiyel", max: 25, color: "bg-blue-200" },
  { key: "contactability", label: "İletişim", max: 15, color: "bg-white" },
] as const;

export default async function LeadDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const lead = getLead(id);
  if (!lead) notFound();
  const signals = lead.websiteSignals;

  return <div className="animate-enter space-y-5">
    <Link href="/leads" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600 hover:text-blue-700"><ArrowLeft className="size-4"/>Lead Explorer’a dön</Link>
    <div className="grid gap-5 xl:grid-cols-12">
      <div className="space-y-5 xl:col-span-8">
        <Card className="relative overflow-hidden p-6 md:p-8"><div className="absolute right-0 top-0 size-64 -translate-y-1/2 translate-x-1/3 rounded-full bg-blue-100/60 blur-3xl"/><div className="relative flex flex-col justify-between gap-6 md:flex-row md:items-center"><div><p className="data-label flex items-center gap-2 text-blue-700"><span className="grid size-8 place-items-center rounded-full bg-blue-600 text-white">{lead.initials}</span>{lead.category}</p><h1 className="mt-4 text-3xl font-bold tracking-[-0.02em]">{lead.name}</h1><div className="mt-4 flex flex-wrap items-center gap-x-4 gap-y-2 text-sm text-slate-600"><span className="flex items-center gap-1 font-semibold text-slate-950"><Star className="size-4 fill-amber-400 text-amber-400"/>{lead.rating} <i className="font-normal not-italic text-slate-500">({lead.reviewCount} yorum)</i></span><span className="flex items-center gap-1"><MapPin className="size-4"/>{lead.district}, {lead.city}</span>{lead.website && <span className="flex items-center gap-1"><Globe2 className="size-4"/>{lead.website}</span>}</div></div><div className="flex flex-col items-start gap-3 md:items-end"><button className="inline-flex h-11 items-center gap-2 rounded-md bg-slate-950 px-5 text-sm font-semibold text-white hover:bg-slate-800"><Mail className="size-4"/>Lead ile iletişime geç</button><span className="mono-data text-[11px] text-slate-500">Keşfedildi: {formatRelativeDate(lead.discoveredAt)}</span></div></div></Card>

        <div className="grid gap-5 md:grid-cols-2">
          <Card className="border-slate-900 bg-[#131b2e] p-7 text-white"><p className="data-label text-blue-200">Fırsat skoru · {lead.score.version}</p><div className="mt-5 flex items-end gap-2"><span className="mono-data text-6xl font-bold">{lead.score.total}</span><span className="mb-1 text-lg text-slate-400">/100</span></div><p className="mt-3 text-sm leading-6 text-slate-300">Güçlü ticari sinyaller ile dijital olgunluk açığının birleşimi.</p><div className="mt-9 space-y-4">{scoreParts.map((part) => { const value = lead.score[part.key]; return <div key={part.key}><div className="mb-1.5 flex justify-between text-xs text-slate-300"><span>{part.label}</span><span className="mono-data">{value}/{part.max}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-white/15"><div className={`h-full rounded-full ${part.color}`} style={{width:`${(value/part.max)*100}%`}}/></div></div>; })}</div></Card>
          <Card className="p-7"><h2 className="flex items-center gap-2 text-lg font-semibold"><Sparkles className="size-5 text-blue-700"/>AI fırsat analizi</h2><p className="mt-5 text-sm leading-6 text-slate-600">{lead.aiSummary}</p><div className="mt-6 space-y-5"><div className="flex gap-3"><CheckCircle2 className="mt-0.5 size-5 shrink-0 text-emerald-500"/><div><p className="data-label text-slate-800">Güçlü yönler</p><p className="mt-2 text-sm leading-6 text-slate-600">{lead.strengths.join(" · ")}</p></div></div><div className="flex gap-3"><XCircle className="mt-0.5 size-5 shrink-0 text-red-600"/><div><p className="data-label text-slate-800">Gelişim alanları</p><p className="mt-2 text-sm leading-6 text-slate-600">{lead.weaknesses.join(" · ")}</p></div></div></div><p className="mt-6 border-t border-slate-200 pt-4 text-[11px] leading-5 text-slate-500">AI yorumu yapılandırılmış tarama verisini açıklar; sayısal skoru değiştirmez.</p></Card>
        </div>

        <Card className="p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-lg font-semibold">Website sağlığı ve teknoloji</h2><p className="mt-1 text-xs text-slate-500">Tespitler yalnızca son taramada gözlemlenen herkese açık sinyallerdir.</p></div><span className="mono-data text-[11px] text-slate-500">Son tarama: {signals.scannedAt ? formatRelativeDate(signals.scannedAt) : "Yok"}</span></div><div className="mt-6 grid gap-4 sm:grid-cols-3"><SignalCard label="Performans" value={signals.performanceScore?.toString() ?? "—"} status={(signals.performanceScore ?? 0) >= 70 ? "good" : "bad"} note={(signals.performanceScore ?? 0) >= 70 ? "Sağlıklı" : "İyileştirme gerekli"}/><SignalCard label="Mobil uyum" value={signals.mobileFriendly === null ? "—" : signals.mobileFriendly ? "Evet" : "Hayır"} status={signals.mobileFriendly ? "good" : "bad"} note={signals.mobileFriendly ? "Mobil uyumlu" : "Viewport sorunu"}/><SignalCard label="Güvenlik" value={signals.httpsEnabled ? "HTTPS" : "HTTP"} status={signals.httpsEnabled ? "good" : "bad"} note={signals.httpsEnabled ? "Güvenli bağlantı" : "HTTPS tespit edilmedi"}/></div><div className="mt-7 grid gap-7 md:grid-cols-2"><DetectionList title="Tespit edilen teknolojiler" items={[signals.ga4Detected && "Google Analytics 4", signals.gtmDetected && "Google Tag Manager", signals.cms, signals.whatsappDetected && "WhatsApp CTA", signals.formDetected && "İletişim formu"].filter(Boolean) as string[]} positive/><DetectionList title="Tespit edilmeyen kritik sinyaller" items={[!signals.metaPixelDetected && "Meta Pixel", !signals.gtmDetected && "Google Tag Manager", !signals.whatsappDetected && "WhatsApp CTA", !signals.formDetected && "İletişim formu"].filter(Boolean) as string[]}/></div></Card>
      </div>

      <aside className="space-y-5 xl:col-span-4">
        <Card className="p-6"><h2 className="text-lg font-semibold">Önerilen hizmetler</h2><p className="mt-2 text-sm leading-6 text-slate-600">Deterministik sinyaller ve fırsat analizi temelinde.</p><div className="mt-5 space-y-2">{lead.recommendedServices.map((service, index) => <label key={service} className="flex cursor-pointer gap-3 rounded-lg p-3 hover:bg-slate-50"><input type="checkbox" defaultChecked={index < 2} className="mt-1 accent-blue-700"/><span><b className="block text-sm font-semibold">{service}</b><small className="mt-1 block text-xs text-slate-500">{index === 0 ? "Yüksek öncelik" : "Büyüme fırsatı"}</small></span></label>)}</div><button className="mt-5 h-10 w-full rounded-md bg-slate-100 text-sm font-semibold text-slate-800 hover:bg-slate-200">Teklif taslağı oluştur</button></Card>
        <Card className="p-6"><h2 className="text-lg font-semibold">İletişim</h2><div className="mt-5 space-y-3 text-sm"><p className="flex items-center gap-3"><Phone className="size-4 text-slate-500"/>{lead.phone ?? "Telefon bulunamadı"}</p><p className="flex items-center gap-3"><Globe2 className="size-4 text-slate-500"/>{lead.website ?? "Website bulunamadı"}</p><p className="flex items-center gap-3"><LockKeyhole className="size-4 text-slate-500"/>{signals.httpsEnabled ? "HTTPS etkin" : "HTTPS tespit edilmedi"}</p></div>{lead.website && <a href={`https://${lead.website}`} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-blue-700 hover:underline">Websiteyi aç <ExternalLink className="size-4"/></a>}</Card>
        <Card className="min-h-80 p-6"><h2 className="text-lg font-semibold">CRM aktivitesi</h2><select defaultValue={lead.status} className="mt-5 h-11 w-full rounded-md border border-slate-200 bg-slate-50 px-3 text-sm"><option value="new">Yeni</option><option value="qualified">Nitelikli</option><option value="contacted">İletişimde</option><option value="interested">İlgileniyor</option><option value="proposal">Teklif</option></select><div className="mt-5 rounded-lg bg-slate-100 p-4"><p className="text-sm leading-5">Lead keşif taramasından oluşturuldu. Skor {lead.score.total} olarak hesaplandı.</p><p className="data-label mt-3 text-slate-500">Sistem · {formatRelativeDate(lead.discoveredAt)}</p></div><textarea className="mt-8 min-h-24 w-full resize-none rounded-lg border border-slate-200 bg-slate-50 p-3 text-sm outline-none focus:border-blue-600" placeholder="Not ekle..."/><button className="mt-2 h-10 w-full rounded-md bg-blue-700 text-sm font-semibold text-white">Notu kaydet</button></Card>
      </aside>
    </div>
  </div>;
}

function SignalCard({ label, value, status, note }: { label: string; value: string; status: "good" | "bad"; note: string }) { return <div className={`rounded-lg p-4 ${status === "good" ? "bg-emerald-50" : "bg-red-50"}`}><p className="data-label text-slate-600">{label}</p><p className={`mono-data mt-3 text-2xl font-bold ${status === "good" ? "text-emerald-700" : "text-red-700"}`}>{value}</p><p className={`mt-2 text-xs ${status === "good" ? "text-emerald-700" : "text-red-700"}`}>{note}</p></div>; }
function DetectionList({ title, items, positive = false }: { title: string; items: string[]; positive?: boolean }) { return <div><h3 className="mono-data border-b border-slate-200 pb-2 text-xs font-semibold uppercase">{title}</h3><ul className="mt-4 space-y-3">{items.length ? items.map((item) => <li key={item} className="flex items-center gap-3 text-sm"><i className={`size-2 rounded-full ${positive ? "bg-blue-700" : "bg-red-600"}`}/><span className={positive ? "text-slate-700" : "text-slate-500 line-through"}>{item}</span></li>) : <li className="text-sm text-slate-500">Kayıt yok</li>}</ul></div>; }

