import type { DiscoveryJob, Lead } from "@krenora/shared";

export const leads: Lead[] = [
  {
    id: "minik-melekler",
    name: "Minik Melekler Anaokulu",
    initials: "MM",
    category: "Anaokulu",
    country: "Türkiye",
    city: "İstanbul",
    district: "Kadıköy",
    website: "minikmelekler.com.tr",
    phone: "+90 216 555 01 24",
    rating: 4.8,
    reviewCount: 180,
    status: "new",
    score: { businessStrength: 28, digitalOpportunity: 25, commercialPotential: 20, contactability: 12, total: 85, version: "v1.0.0" },
    websiteSignals: { reachable: true, httpsEnabled: true, performanceScore: 38, seoScore: 46, mobileFriendly: false, ga4Detected: true, gtmDetected: false, metaPixelDetected: false, whatsappDetected: false, formDetected: true, cms: "WordPress 5.8", scannedAt: "2026-08-29T08:00:00+03:00" },
    recommendedServices: ["Mobil öncelikli web tasarımı", "Analytics & tracking kurulumu", "Yerel SEO"],
    strengths: ["Yüksek yorum hacmi", "Güçlü yerel itibar", "Doğrulanmış Google işletme profili"],
    weaknesses: ["Düşük mobil performans", "GTM ve Meta Pixel tespit edilmedi", "Zayıf dönüşüm çağrıları"],
    aiSummary: "İşletmenin güçlü yerel itibarı ve yüksek yorum hacmi gerçek talebe işaret ediyor. Buna karşın web sitesi yavaş, mobil deneyimi zayıf ve dönüşüm ölçüm altyapısı eksik. Dijital iyileştirmeler mevcut talebin daha verimli satışa dönüşmesini sağlayabilir.",
    discoveredAt: "2026-08-29T07:10:00+03:00",
  },
  {
    id: "pirlanta-dis-klinigi",
    name: "Pırlanta Diş Kliniği",
    initials: "PD",
    category: "Diş Kliniği",
    country: "Türkiye",
    city: "İstanbul",
    district: "Beşiktaş",
    website: null,
    phone: "+90 212 555 42 10",
    rating: 4.9,
    reviewCount: 340,
    status: "contacted",
    score: { businessStrength: 30, digitalOpportunity: 27, commercialPotential: 23, contactability: 8, total: 88, version: "v1.0.0" },
    websiteSignals: { reachable: false, httpsEnabled: false, performanceScore: null, seoScore: null, mobileFriendly: null, ga4Detected: false, gtmDetected: false, metaPixelDetected: false, whatsappDetected: false, formDetected: false, cms: null, scannedAt: "2026-08-28T14:20:00+03:00" },
    recommendedServices: ["Kurumsal web sitesi", "Meta Ads", "Dönüşüm takibi"],
    strengths: ["Çok güçlü hasta memnuniyeti", "Yüksek yorum hacmi", "Telefon bilgisi mevcut"],
    weaknesses: ["Web sitesi bulunamadı", "Dijital dönüşüm altyapısı gözlemlenemedi"],
    aiSummary: "Çok güçlü itibar sinyallerine rağmen resmi web sitesi bulunmuyor. Bu durum markalı aramalarda güven, hizmet anlatımı ve ölçülebilir talep üretimi açısından önemli bir fırsat yaratıyor.",
    discoveredAt: "2026-08-28T12:00:00+03:00",
  },
  {
    id: "moda-veteriner",
    name: "Moda Veteriner Kliniği",
    initials: "MV",
    category: "Veteriner",
    country: "Türkiye",
    city: "İstanbul",
    district: "Kadıköy",
    website: "modaveteriner.com",
    phone: "+90 216 555 18 18",
    rating: 4.5,
    reviewCount: 112,
    status: "qualified",
    score: { businessStrength: 22, digitalOpportunity: 16, commercialPotential: 16, contactability: 13, total: 67, version: "v1.0.0" },
    websiteSignals: { reachable: true, httpsEnabled: true, performanceScore: 64, seoScore: 72, mobileFriendly: true, ga4Detected: true, gtmDetected: true, metaPixelDetected: false, whatsappDetected: true, formDetected: false, cms: "WordPress", scannedAt: "2026-08-27T16:30:00+03:00" },
    recommendedServices: ["İtibar yönetimi", "Form optimizasyonu"],
    strengths: ["İyi yerel itibar", "Mobil uyumlu web sitesi", "WhatsApp çağrısı mevcut"],
    weaknesses: ["Form tespit edilmedi", "Meta Pixel tespit edilmedi"],
    aiSummary: "Dijital temelleri mevcut olan işletmede en belirgin fırsat, dönüşüm noktalarının güçlendirilmesi ve reklam ölçüm altyapısının tamamlanmasıdır.",
    discoveredAt: "2026-08-27T15:00:00+03:00",
  },
  {
    id: "mavi-izler-anaokulu",
    name: "Mavi İzler Anaokulu",
    initials: "Mİ",
    category: "Anaokulu",
    country: "Türkiye",
    city: "İstanbul",
    district: "Üsküdar",
    website: "maviizler.com.tr",
    phone: "+90 216 555 77 31",
    rating: 4.7,
    reviewCount: 96,
    status: "reviewing",
    score: { businessStrength: 24, digitalOpportunity: 23, commercialPotential: 19, contactability: 13, total: 79, version: "v1.0.0" },
    websiteSignals: { reachable: true, httpsEnabled: true, performanceScore: 44, seoScore: 51, mobileFriendly: true, ga4Detected: false, gtmDetected: false, metaPixelDetected: false, whatsappDetected: true, formDetected: true, cms: "Wix", scannedAt: "2026-08-26T09:15:00+03:00" },
    recommendedServices: ["Performans optimizasyonu", "Analytics kurulumu", "Yerel SEO"],
    strengths: ["Yüksek puan", "İletişim kanalları güçlü"],
    weaknesses: ["Düşük performans", "Analytics ve reklam etiketleri tespit edilmedi"],
    aiSummary: "İşletmenin güçlü itibarı, düşük web performansı ve eksik ölçüm altyapısı nedeniyle anlamlı bir dijital büyüme fırsatı bulunuyor.",
    discoveredAt: "2026-08-26T08:30:00+03:00",
  },
  {
    id: "dent-plus",
    name: "Dent Plus Ağız ve Diş Sağlığı",
    initials: "DP",
    category: "Diş Kliniği",
    country: "Türkiye",
    city: "İstanbul",
    district: "Şişli",
    website: "dentplusistanbul.com",
    phone: "+90 212 555 09 09",
    rating: 4.6,
    reviewCount: 226,
    status: "interested",
    score: { businessStrength: 27, digitalOpportunity: 19, commercialPotential: 22, contactability: 14, total: 82, version: "v1.0.0" },
    websiteSignals: { reachable: true, httpsEnabled: true, performanceScore: 53, seoScore: 61, mobileFriendly: true, ga4Detected: true, gtmDetected: false, metaPixelDetected: false, whatsappDetected: true, formDetected: true, cms: "Webflow", scannedAt: "2026-08-25T11:45:00+03:00" },
    recommendedServices: ["Teknik SEO", "GTM & Meta Pixel", "Landing page optimizasyonu"],
    strengths: ["Yüksek yorum hacmi", "İyi web temeli", "Çoklu iletişim kanalı"],
    weaknesses: ["Orta düzey performans", "Reklam ölçüm etiketleri tespit edilmedi"],
    aiSummary: "Sağlam ticari sinyaller ve çalışan web altyapısı mevcut. En hızlı kazanım, teknik SEO ile reklam ölçümünün olgunlaştırılması olacaktır.",
    discoveredAt: "2026-08-25T10:20:00+03:00",
  },
];

export const discoveryJobs: DiscoveryJob[] = [
  { id: "job-1", title: "Diş Klinikleri", location: "İzmir · Bornova, Karşıyaka +2", status: "completed", progress: 100, recordsFound: 342, createdAt: "2026-08-29T05:00:00+03:00" },
  { id: "job-2", title: "Butik Oteller", location: "Antalya · Kaş, Kalkan", status: "running", progress: 45, recordsFound: 120, createdAt: "2026-08-29T07:30:00+03:00" },
  { id: "job-3", title: "Spor Salonları", location: "Ankara · Çankaya", status: "completed", progress: 100, recordsFound: 89, createdAt: "2026-08-28T12:00:00+03:00" },
];

export function getLead(id: string) {
  return leads.find((lead) => lead.id === id);
}

