"use client";

import type { Lead, LeadStatus } from "@krenora/shared";
import { ChevronRight, Globe2, MapPin, Search, Star } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";
import { ScoreRing } from "@/components/score-ring";

const statusLabels: Record<LeadStatus, string> = { new: "Yeni", qualified: "Nitelikli", reviewing: "İnceleniyor", contacted: "İletişimde", interested: "İlgileniyor", proposal: "Teklif", won: "Kazanıldı", lost: "Kaybedildi", not_relevant: "Uygun değil" };
const statusColors: Record<LeadStatus, string> = { new: "bg-blue-600", qualified: "bg-emerald-500", reviewing: "bg-amber-500", contacted: "bg-violet-500", interested: "bg-cyan-500", proposal: "bg-orange-500", won: "bg-emerald-700", lost: "bg-red-600", not_relevant: "bg-slate-400" };

export function LeadExplorer({ leads }: { leads: Lead[] }) {
  const [query, setQuery] = useState("");
  const [minScore, setMinScore] = useState(70);
  const [minRating, setMinRating] = useState(4);
  const [category, setCategory] = useState("Tümü");
  const categories = ["Tümü", ...new Set(leads.map((lead) => lead.category))];
  const filtered = useMemo(() => leads.filter((lead) => lead.score.total >= minScore && lead.rating >= minRating && (category === "Tümü" || lead.category === category) && lead.name.toLocaleLowerCase("tr").includes(query.toLocaleLowerCase("tr"))).sort((a,b) => b.score.total-a.score.total), [leads, query, minScore, minRating, category]);

  return <div className="grid gap-6 xl:grid-cols-[280px_minmax(0,1fr)]">
    <aside className="h-fit rounded-xl border border-slate-200 bg-slate-100 p-5 shadow-sm"><div className="flex items-center justify-between border-b border-slate-200 pb-4"><h2 className="text-lg font-semibold">Filtreler</h2><button onClick={() => { setQuery(""); setMinScore(70); setMinRating(4); setCategory("Tümü"); }} className="text-xs font-semibold text-blue-700">Sıfırla</button></div><div className="space-y-6 pt-5"><label className="block"><span className="data-label text-slate-600">Fırsat skoru</span><div className="mono-data mt-3 flex justify-between text-xs"><span>Min: {minScore}</span><span>Max: 100</span></div><input className="mt-3 w-full accent-blue-700" type="range" min="0" max="100" value={minScore} onChange={(e) => setMinScore(Number(e.target.value))}/></label><div><span className="data-label text-slate-600">Minimum puan</span><div className="mt-3 grid grid-cols-3 gap-2">{[3,4,4.5].map((value) => <button key={value} onClick={() => setMinRating(value)} className={`h-9 rounded-md text-xs font-semibold shadow-sm ${minRating === value ? "bg-blue-700 text-white" : "bg-white text-slate-700"}`}>{value}+</button>)}</div></div><label className="block"><span className="data-label text-slate-600">Kategori</span><select value={category} onChange={(e) => setCategory(e.target.value)} className="mt-3 h-10 w-full rounded-md border border-slate-200 bg-white px-3 text-sm outline-none focus:ring-2 focus:ring-blue-500/30">{categories.map((item) => <option key={item}>{item}</option>)}</select></label><div><span className="data-label text-slate-600">Bölge</span><div className="mt-3 flex flex-wrap gap-2">{["Kadıköy", "Beşiktaş", "Üsküdar"].map((item) => <span key={item} className="rounded bg-slate-200 px-2 py-1 text-xs font-medium">{item}</span>)}</div></div></div></aside>
    <section className="min-w-0 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-200 bg-slate-100 p-4 sm:flex-row sm:items-center"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 size-5 -translate-y-1/2 text-slate-500"/><input value={query} onChange={(e) => setQuery(e.target.value)} className="h-11 w-full rounded-md border border-slate-200 bg-white pl-10 pr-4 text-sm outline-none focus:border-blue-600 focus:ring-2 focus:ring-blue-500/20" placeholder="İşletme adına göre ara..." /></label><span className="mono-data shrink-0 text-xs text-slate-500">{filtered.length} sonuç</span></div>
      <div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[900px] border-collapse text-left"><thead className="border-b border-slate-200 bg-slate-50"><tr className="data-label text-slate-600"><th className="px-5 py-4">İşletme</th><th className="px-4 py-4">Kategori / Bölge</th><th className="px-4 py-4">Google verisi</th><th className="px-4 py-4">Fırsat skoru</th><th className="px-4 py-4">Önerilen hizmetler</th><th className="px-4 py-4">Durum</th><th className="w-10" /></tr></thead><tbody className="divide-y divide-slate-200">{filtered.map((lead) => <tr key={lead.id} className="group hover:bg-slate-50"><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="grid size-11 shrink-0 place-items-center rounded-lg bg-slate-200 text-sm font-bold text-slate-700">{lead.initials}</div><div className="min-w-0"><Link href={`/leads/${lead.id}`} className="block max-w-52 truncate font-semibold group-hover:text-blue-700">{lead.name}</Link><p className="mono-data mt-1 flex items-center gap-1 text-[11px] text-slate-500"><Globe2 className="size-3.5"/>{lead.website ?? "Website yok"}</p></div></div></td><td className="px-4 py-4 text-sm"><p className="font-medium">{lead.category}</p><p className="mt-1 flex items-center gap-1 text-slate-500"><MapPin className="size-3.5"/>{lead.district}</p></td><td className="px-4 py-4"><p className="mono-data flex items-center gap-1 text-sm font-semibold"><Star className="size-4 fill-amber-400 text-amber-400"/>{lead.rating}</p><p className="mono-data mt-1 text-[11px] text-slate-500">{lead.reviewCount} yorum</p></td><td className="px-4 py-3"><ScoreRing value={lead.score.total}/></td><td className="px-4 py-4"><div className="flex max-w-64 flex-wrap gap-1.5">{lead.recommendedServices.slice(0,2).map((service) => <span key={service} className="rounded bg-blue-50 px-2 py-1 text-[11px] font-semibold text-blue-950">{service}</span>)}</div></td><td className="px-4 py-4"><span className="inline-flex items-center gap-2 whitespace-nowrap rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-bold uppercase tracking-wide"><i className={`size-1.5 rounded-full ${statusColors[lead.status]}`}/>{statusLabels[lead.status]}</span></td><td><Link href={`/leads/${lead.id}`} aria-label={`${lead.name} detayına git`}><ChevronRight className="size-4 text-slate-400"/></Link></td></tr>)}</tbody></table></div>
      <div className="divide-y divide-slate-200 md:hidden">{filtered.map((lead) => <Link href={`/leads/${lead.id}`} key={lead.id} className="block p-4 hover:bg-slate-50"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{lead.name}</p><p className="mt-1 text-xs text-slate-500">{lead.category} · {lead.district}</p><p className="mt-3 flex items-center gap-1 text-xs"><Star className="size-3.5 fill-amber-400 text-amber-400"/>{lead.rating} · {lead.reviewCount} yorum</p></div><ScoreRing value={lead.score.total}/></div></Link>)}</div>
      {filtered.length === 0 && <div className="grid min-h-72 place-items-center p-8 text-center"><div><Search className="mx-auto size-8 text-slate-400"/><p className="mt-3 font-semibold">Bu filtrelerle eşleşen lead bulunamadı.</p><p className="mt-1 text-sm text-slate-500">Skor veya kategori filtrelerini genişletin.</p></div></div>}
    </section>
  </div>;
}

